name: sci-vis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - fastapi
  - uvicorn
  - websockets
  - pytest
  - xarray
  - pandas
  - matplotlib
  - netCDF4
  - dask
  - boto3
  - ipykernel
  - pip
  - pip:
      - "panel[codeeditor]"
      - meshio
      - openvisuspy
      - colorcet
      - xmltodict
      - OpenVisus
      - locust
